### ISSUE TITLE
rapid crashes on list-tags

### ISSUE THREAD

**Issue by abma** [tvo/rapid#9] opened 2010-08-31 00:26 UTC
this suddenly happened yesterday... i think it's an problem on parsing the versions.gz files.

http://pastebin.com/kzkMVvGY

**Comment by tvo** [comment] 2010-08-31 16:16
Confirmed, it breaks everything actually, not just list-tags :-o

**Comment by tvo** [comment] 2010-08-31 18:02
It's because Conflict Terra v1.02 is 5 times in the list with different MD5 hashes. Wondering now how to solve :-)

**Comment by abma** [comment] 2010-08-31 21:57
don't allow to chose a tag (server-side) that already exists? :-)
downloading by md5sum isn't really useful i think, because the user had to chose which md5 he wants...

btw. currently it seems to work again :)

**Comment by tvo** [comment] 2010-09-01 08:10
I discussed with det and we came to the conclusion that duplicate names shouldn't be allowed. So probably he fixed the versions.gz file on the server.

I'll keep this open until I've made rapid a bit more resistant against such things. (Just ignoring the duplicate packages or so, instead of immediatlely exiting with an error...)

**Comment by tvo** [comment] 2010-09-03 20:02
don't choke on multiple packages with same name, but different hex or dependencies

All but the first package with that name will be ignored completely.
Closed by a884731f2defd950782a8bfeb9eaf10d05a3dcc6

**Closed as completed by tvo** 2010-09-03 20:02 UTC
